package com.civicfa1.dashboard;

import android.content.Context;
import android.view.View;
import java.util.ArrayList;
import java.util.List;

final class DiagnosticsScreenView extends RefLayout {
    private final ActionButtonView[] menu=new ActionButtonView[7];
    private final SensorCardView[] live=new SensorCardView[12];
    private final InfoPanelView status,scan,detail;
    private int section=0;
    private final String[] labels={"LIVE DATA","DTC CODES","READINESS","FREEZE FRAME","O2 SENSORS","ON-BOARD TEST","VEHICLE INFO"};
    DiagnosticsScreenView(Context c){super(c);setBackgroundColor(Ui.BG);for(int i=0;i<labels.length;i++){menu[i]=new ActionButtonView(c,labels[i],Ui.DIAG);final int idx=i;menu[i].setOnClickListener(v->setSection(idx));addRef(menu[i],15,125+i*66,250,55);}SensorType[] types={SensorType.RPM,SensorType.SPEED,SensorType.COOLANT,SensorType.INTAKE,SensorType.THROTTLE,SensorType.MAP,SensorType.MAF,SensorType.SHORT_FUEL_TRIM,SensorType.LONG_FUEL_TRIM,SensorType.MODULE_VOLTAGE,SensorType.FUEL_LEVEL,SensorType.TIMING};int k=0;for(int r=0;r<4;r++)for(int col=0;col<3;col++){SensorCardView card=new SensorCardView(c,types[k],Ui.DIAG);card.setClickable(false);live[k]=card;addRef(card,285+col*200,125+r*112,190,102);k++;}status=new InfoPanelView(c,"DIAGNOSTICS STATUS",Ui.DIAG);scan=new InfoPanelView(c,"VEHICLE SYSTEM SCAN",Ui.DIAG);detail=new InfoPanelView(c,"DETAIL",Ui.DIAG);addRef(status,900,125,365,205);addRef(scan,900,340,365,230);addRef(detail,285,125,600,448);setSection(0);}
    private void setSection(int s){section=s;for(int i=0;i<menu.length;i++)menu[i].setSelectedState(i==s);boolean liveMode=s==0;for(SensorCardView c:live)c.setVisibility(liveMode?View.VISIBLE:View.GONE);detail.setVisibility(liveMode?View.GONE:View.VISIBLE);}
    void update(ObdManager.State state,ObdManager.Telemetry t,ObdManager.Readiness r,ObdManager.DtcResult d){boolean connected=state==ObdManager.State.ECU_CONNECTED;long now=System.currentTimeMillis();for(SensorCardView card:live){SensorType s=card.getSensor();boolean unsupported=!s.supported(t);boolean ok=connected&&!unsupported&&!Float.isNaN(s.value(t))&&s.at(t)>0&&now-s.at(t)<=s.ttlMs();card.setReading(s.value(t),ok,unsupported);}int complete=0,supported=0;for(ObdManager.MonitorState ms:r.monitors.values()){if(ms!=ObdManager.MonitorState.UNSUPPORTED){supported++;if(ms==ObdManager.MonitorState.COMPLETE)complete++;}}status.setLines("ECU CONNECTION:  "+(connected?"CONNECTED":"--"),"PROTOCOL:  "+empty(t.protocol),"DTC CODES:  "+dtcCount(d),"READINESS:  "+(r.available?complete+" / "+supported:"--"));scan.setLines("ENGINE:  "+(connected?"OK":"--"),"ABS:  --","SRS:  --","TRANSMISSION:  --","BCM:  --");if(section!=0)detail.setLines(detailLines(section,t,r,d));}
    private String[] detailLines(int s,ObdManager.Telemetry t,ObdManager.Readiness r,ObdManager.DtcResult d){List<String> out=new ArrayList<>();out.add(labels[s]);if(s==1){out.add("Status: "+d.status);out.add("Stored codes: "+(d.codes.isEmpty()?"--":d.codes.toString()));out.add(d.detail);}else if(s==2){out.add("MIL: "+(r.available?(r.milOn?"ON":"OFF"):"--"));for(java.util.Map.Entry<String,ObdManager.MonitorState> e:r.monitors.entrySet())out.add(e.getKey()+": "+e.getValue());}else if(s==3){out.add("Freeze-frame capture is shown only when supported by the ECU.");out.add("No fabricated values are displayed.");}else if(s==4){out.add("O2 sensor live values require supported O2 PIDs.");out.add("Unsupported data remains N/A.");}else if(s==5){out.add("On-board test results are not auto-cleared.");out.add("Mode 04 is never sent automatically.");}else if(s==6){out.add("Protocol: "+empty(t.protocol));out.add("Adapter: "+empty(t.adapterVersion));out.add("Supported PIDs: "+(t.capabilitiesKnown?t.supportedPids.size():0));}return out.toArray(new String[0]);}
    private static String empty(String s){return s==null||s.trim().isEmpty()?"--":s;}private static String dtcCount(ObdManager.DtcResult d){if(d==null||d.status==ObdManager.DtcStatus.NOT_READ)return"--";return Integer.toString(d.codes.size());}
}
